### ISSUE TITLE
download the module from registry

### ISSUE THREAD

**Issue by roeymizrachi** [claranet/terraform-azurerm-vnet-peering#4]
hi , 

In the last 2 days I cant download the module from the terraform registry.
the failure occured during the 'terraform init' command.
the error is:

Could not download module "vnet_peering"
"https://github.com/Azure/terraform-azurerm-vnetpeering/archive/v1.0.0.tar.gz//*?archive=tar.gz":
bad response code: 404.

Thanks

**Comment by BzSpi** [comment]
Hi @roeymizrachi  

Can you paste the code you use in order to call the module please ? 
The URL you gave us use the Azure github repository and not ours.

**Comment by Shr3ps** [comment]
Hello, we got this too, but it's quite random from the Terraform registry.
I saw someone opened an issue too here: https://github.com/hashicorp/terraform/issues/24490

You can add some more infos on it.
On the other hand, verify you're using Terraform 0.12.24 and a workaround is to use the github link instead of the registry one if it still doesn't work with TF 0.12.24:
```
module "vnet-peering" {
  source = "github.com/claranet/terraform-azurerm-vnet-peering?ref=v2.1.2"
```

**Comment by roeymizrachi** [comment]
@BzSpi 
You are right - I am using Azure GitHub repository and not yours.

Thanks
